#ifndef PARAMETERS_H
#define PARAMETERS_H

#define PARAM_SECURITY 128
#define PARAM_LABEL "sdith-251-L1-tprs-ext"

#ifdef PARAM_SEL1
#define PARAM_SELECTOR_DEGREE 1
#define PARAM_CIRCUIT_DEPTH 2
#define PARAM_NB_EXECUTIONS 19
#endif
#ifdef PARAM_SEL2
#define PARAM_SELECTOR_DEGREE 2
#define PARAM_CIRCUIT_DEPTH 3
#define PARAM_NB_EXECUTIONS 20
#endif
#ifdef PARAM_SEL3
#define PARAM_SELECTOR_DEGREE 3
#define PARAM_CIRCUIT_DEPTH 4
#define PARAM_NB_EXECUTIONS 22
#endif
#ifdef PARAM_SEL4
#define PARAM_SELECTOR_DEGREE 4
#define PARAM_CIRCUIT_DEPTH 5
#define PARAM_NB_EXECUTIONS 23
#endif

// SD Parameters
#define PARAM_FIELD_SIZE 251
#define PARAM_CODE_LENGTH 230
#define PARAM_CODE_DIMENSION 126
#define PARAM_CODE_WEIGHT 79

// MPC Parameters
#define PARAM_eta 16

// MPCitH Parameters
#define PARAM_NB_PARTIES PARAM_FIELD_SIZE
#define PARAM_LOG_NB_PARTIES 8

// Signature Parameters
#define PARAM_SEED_SIZE (128/8)
#define PARAM_SALT_SIZE (256/8)
#define PARAM_DIGEST_SIZE (256/8)

// Hash Domain Separation
#define HASH_PREFIX_COMMITMENT 0
#define HASH_PREFIX_FIRST_CHALLENGE 1
#define HASH_PREFIX_SECOND_CHALLENGE 2
#define HASH_PREFIX_THIRD_CHALLENGE 3
#define HASH_PREFIX_SEED_TREE 4

// Misc
#ifndef PARAM_SPLITTING_FACTOR
#define PARAM_SPLITTING_FACTOR 1
#endif
#ifndef PARAM_NB_EVALS_PER_POLY
#define PARAM_NB_EVALS_PER_POLY 1
#endif

#define PARAM_CHUNK_LENGTH (PARAM_CODE_LENGTH/PARAM_SPLITTING_FACTOR)
#define PARAM_CHUNK_WEIGHT (PARAM_CODE_WEIGHT/PARAM_SPLITTING_FACTOR)

#define PARAM_SYNDROME_LENGTH (PARAM_CODE_LENGTH-PARAM_CODE_DIMENSION)
#define PARAM_SYNDROME_LENGTH_CEIL32 (((PARAM_SYNDROME_LENGTH+31)>>5)<<5)
#define PARAM_CODEWORD_LENGTH (PARAM_CODE_LENGTH)
#define PARAM_CODEWORD_LENGTH_CEIL32 (((PARAM_CODEWORD_LENGTH+31)>>5)<<5)
#define PARAM_PLAINTEXT_LENGTH (PARAM_CODE_DIMENSION)
#define PARAM_PCMATRIX_BYTESIZE (PARAM_CODE_DIMENSION*PARAM_SYNDROME_LENGTH_CEIL32)

#endif /* PARAMETERS_H */
