#ifndef PARAMETERS_H
#define PARAMETERS_H

#define PARAM_SECURITY 256
#define PARAM_LABEL "fr23-sd-251-L5-threshold-extended"

// SD Parameters
#define PARAM_FIELD_SIZE 251
#define PARAM_CODE_LENGTH 480
#define PARAM_CODE_DIMENSION 278
#define PARAM_CODE_WEIGHT 150
#define PARAM_SPLITTING_FACTOR 2

// MPC Parameters
#define PARAM_eta 32
#define PARAM_eta_dc 36

// MPCitH Parameters
#define PARAM_NB_EXECUTIONS 37
#define PARAM_NB_PARTIES PARAM_FIELD_SIZE
#define PARAM_LOG_NB_PARTIES 8

// Signature Parameters
#define PARAM_SEED_SIZE (256/8)
#define PARAM_SALT_SIZE (512/8)
#define PARAM_DIGEST_SIZE (512/8)

// Hash Domain Separation
#define HASH_PREFIX_COMMITMENT 0
#define HASH_PREFIX_FIRST_CHALLENGE 1
#define HASH_PREFIX_SECOND_CHALLENGE 2
#define HASH_PREFIX_THIRD_CHALLENGE 3
#define HASH_PREFIX_SEED_TREE 4
#define HASH_PREFIX_MERKLE_TREE 4

// Misc
#ifndef PARAM_SPLITTING_FACTOR
#define PARAM_SPLITTING_FACTOR 1
#endif
#ifndef PARAM_NB_EVALS_PER_POLY
#define PARAM_NB_EVALS_PER_POLY 1
#endif

#define PARAM_CHUNK_LENGTH (PARAM_CODE_LENGTH/PARAM_SPLITTING_FACTOR)
#define PARAM_CHUNK_WEIGHT (PARAM_CODE_WEIGHT/PARAM_SPLITTING_FACTOR)

#define PARAM_SYNDROME_LENGTH (PARAM_CODE_LENGTH-PARAM_CODE_DIMENSION)
#define PARAM_SYNDROME_LENGTH_CEIL32 (((PARAM_SYNDROME_LENGTH+31)>>5)<<5)
#define PARAM_CODEWORD_LENGTH (PARAM_CODE_LENGTH)
#define PARAM_CODEWORD_LENGTH_CEIL32 (((PARAM_CODEWORD_LENGTH+31)>>5)<<5)
#define PARAM_PLAINTEXT_LENGTH (PARAM_CODE_DIMENSION)
#define PARAM_PCMATRIX_BYTESIZE (PARAM_CODE_DIMENSION*PARAM_SYNDROME_LENGTH_CEIL32)

#endif /* PARAMETERS_H */
